language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install
#  - cd functions && npm install

script:
  - CI=false npm run build
  - firebase deploy --only hosting --token $FIREBASE_DEPLOY_TOKEN

after_script:
  - echo "Done"